### PR TITLE
fixed TOC display in columns

### PR DESCRIPTION
**Pull request by dialegein**
pageBlock.value.content  does not contain nested blocks
https://github.com/craigary/nobelium/issues/138#issue-907925850

### CODE REVIEW

**Comment by normdoow** [comment]
@dialegein Can you share a notion page Id that has an example of this issue that we can test?

**Comment by dialegein** [comment]
> @dialegein Can you share a notion page Id that has an example of this issue that we can test?

1173a216ce144410b2796955dbb9b1bb

**Comment by normdoow** [comment]
@dialegein so currently the TOC only appears if the header is in the first column correct? But not if it is in a secondary collumn.
The images from the issue are a little confusing as to which usecase they are testing.

**Comment by dialegein** [comment]
> @dialegein so currently the TOC only appears if the header is in the first column correct? But not if it is in a secondary collumn.
> The images from the issue are a little confusing as to which usecase they are testing.

the issue is that  the TOC may lose some headers, if header in columns. whether it’s the first or second column.sorry my English is poor so I may not explain clearly

**Review by normdoow — APPROVED** [review]
Looks good!

**Comment by normdoow** [comment]
Live in version 4.7.8!

**Comment by transitive-bullshit** [comment]
Hmmm, the order of the blocks in the recordMap doesn't necessarily match the order of the blocks in the page... I'm not sure if it's safe to rely on this?

**Comment by normdoow** [comment]
> Hmmm, the order of the blocks in the recordMap doesn't necessarily match the order of the blocks in the page... I'm not sure if it's safe to rely on this?

Ah, I did not think of that. Though I haven't seen too many weird issues with that so far with the sites I've seen.

**Pull request merged**
