### PR TITLE
Fix for getting signed urls

### LINKED ISSUE #331: NotionAPI getSignedfileUrls error HTTPError: Response code 400 (Bad Request)
#### Description
All the static builds were fine up until 22nd July 2022, but since yesterday, I have started getting these errors in my build, and oddly, my development builds have become super slow.

This is the log I get while building both static production and SSR development builds.
```
NotionAPI getSignedfileUrls error HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/home/runner/work/pipe-runner-website/pipe-runner-website/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) ***
  code: undefined,
  timings: ***
    start: 1658648256775,
    socket: 1658648256776,
    lookup: 1658648256785,
    connect: 1658648256794,
    secureConnect: 1658648256804,
    upload: 1658648256804,
    response: 1658648256918,
    end: 1658648256918,
    error: undefined,
    abort: undefined,
    phases: ***
      wait: 1,
      dns: 9,
      tcp: 9,
      tls: 10,
      request: 0,
      firstByte: 114,
      download: 0,
      total: 1[43](https://github.com/Pipe-Runner-Lab/pipe-runner-website/runs/7486332222?check_suite_focus=true#step:7:44)
    ***
  ***
***
```

#### Notion Test Page ID

As far as I can tell, this is not a page-specific issue since earlier, the same pages have been working fine for me.
Also, I have done a shallow check and it seems the pages are rendered all right, but I am not sure yet.

#### Version

"notion-client": "5.0.0",
"notion-types": "5.0.0",
"notion-utils": "5.0.0",
"react-notion-x": "5.0.0"

Has something changed from Notion again?? 😢

### PR DESCRIPTION
**Pull request by pbteja1998**
Notion API is throwing an error when a signed URL is requested for page cover.  Removing it solves the problem.

Resolves #331

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Won't this break user-uploaded page covers which need to be signed?

**Comment by pbteja1998** [comment]
I am using this patch in feather.so and so far it is working well even for user uploaded covers. My guess is user uploaded covers were not needed to be signed in the first place.

**Comment by pbteja1998** [comment]
I just tried it locally, the covers are showing up even if they are user-uploaded.

**Comment by remorses** [comment]
Your PR still fails with pages like this one  (the link is using code from your pr)
https://react-notion-x-minimal-demo-git-fork-pbteja1998-patch-2-saasify.vercel.app/5af3d63c840e458e92c09c2ec6cd71b3

The problem is that the signed urls endpoint no longer accepts any host and only accepts domains with host `secure.notion-static.com` (and moaybe also other hosts i dont know about)

This means that if you have any embed on the page addSignedUrls will fail because it passes the embed url to the endpoint (in the page about it passes the loom video url)

**Comment by pbteja1998** [comment]
@remorses can you check your example now?

**Comment by normdoow** [comment]
Is this a different way to fix the same problem as this fixes? https://github.com/NotionX/react-notion-x/pull/332

**Comment by pbteja1998** [comment]
@normdoow yes

**Comment by transitive-bullshit** [comment]
Going with #332 over this PR as I think it's the safer option.

**Pull request closed without merging**
