### PR TITLE
feat: support for normalize chinese title

### PR DESCRIPTION
**Pull request by vv13**
fix for issue #176 .

### CODE REVIEW

**Comment by normdoow** [comment]
This looks good. Makes sense. One thing I'm not sure about. Do Chinese characters work as urls in all browsers?

**Comment by vv13** [comment]
> This looks good. Makes sense. One thing I'm not sure about. Do Chinese characters work as urls in all browsers?

URL use [RFC-1738](https://www.ietf.org/rfc/rfc1738.txt), It basically support us-ascii sets, browsers will encode chinese charaters automatically, but there are differences between different browsers.

As far as i know,  some old browser like IE also support encode character to gb2312.

for this PR, It simply make `getCanonicalPageId` can also get chinese readable title, and if we use it as URL, almost all browser will automatically convert it to URL character set.

**Comment by normdoow** [comment]
Looking good. thanks for this!

**Comment by normdoow** [comment]
added to v4.11.4

**Pull request merged**
