### PR TITLE
fix bug from new notion update

### PR DESCRIPTION
**Pull request by TrillCyborg**

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Thanks, Jason!

**Comment by transitive-bullshit** [comment]
@dividenconquer would you mind posting the notion page ID that you're using so I can try to reproduce the issue?

From my tests, it seems to be working with `100`.

**Comment by dividenconquer** [comment]
c668f987c64a4630b0b988617e49cf34
I am working on this ID, but no luck.

**Comment by transitive-bullshit** [comment]
Hmmm, https://react-notion-x-demo.transitivebullsh.it/c668f987c64a4630b0b988617e49cf34 seems to be rendering okay (it's up-to-date with the latest `react-notion-x` code using `100` for the value).

Is your problem solved when you change the value to `30`?

This might be related to the collection query as opposed to the `loadPageChunk` call.

**Comment by dividenconquer** [comment]
hmm actually no,

I am getting `NotionAPI collectionQuery error Response code 400 (Bad Request)` 
everytime I use` notion.getPage()`

Is there any guesswork for this error? 

Thank you for your help

**Comment by transitive-bullshit** [comment]
@dividenconquer @TrillCyborg possibly related: https://github.com/splitbee/notion-api-worker/pull/39

**Pull request merged**
